import "@/styles/global.css"
import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  const header = (
    <header>
      Temp header.. 🗿
      <Link href={"/"}>Home</Link>
    </header>
  );

  const footer = (
    <footer>
      Temp footer... 🦶
    </footer>
  );

  return (
    < html lang="en" >
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html >
  )
}
